/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AutocompleteAnchor: typeof import('reka-ui')['AutocompleteAnchor']
    AutocompleteContent: typeof import('reka-ui')['AutocompleteContent']
    AutocompleteEmpty: typeof import('reka-ui')['AutocompleteEmpty']
    AutocompleteGroup: typeof import('reka-ui')['AutocompleteGroup']
    AutocompleteInput: typeof import('reka-ui')['AutocompleteInput']
    AutocompleteItem: typeof import('reka-ui')['AutocompleteItem']
    AutocompleteLabel: typeof import('reka-ui')['AutocompleteLabel']
    AutocompleteRoot: typeof import('reka-ui')['AutocompleteRoot']
    AutocompleteSeparator: typeof import('reka-ui')['AutocompleteSeparator']
    AutocompleteTrigger: typeof import('reka-ui')['AutocompleteTrigger']
    AutocompleteViewport: typeof import('reka-ui')['AutocompleteViewport']
    AvatarImage: typeof import('reka-ui')['AvatarImage']
    AvatarRoot: typeof import('reka-ui')['AvatarRoot']
    ComDialog: typeof import('./../components/comDialog.vue')['default']
    DialogClose: typeof import('reka-ui')['DialogClose']
    DialogContent: typeof import('reka-ui')['DialogContent']
    DialogDescription: typeof import('reka-ui')['DialogDescription']
    DialogOverlay: typeof import('reka-ui')['DialogOverlay']
    DialogPortal: typeof import('reka-ui')['DialogPortal']
    DialogRoot: typeof import('reka-ui')['DialogRoot']
    DialogTitle: typeof import('reka-ui')['DialogTitle']
    DialogTrigger: typeof import('reka-ui')['DialogTrigger']
    HoverCardArrow: typeof import('reka-ui')['HoverCardArrow']
    HoverCardContent: typeof import('reka-ui')['HoverCardContent']
    HoverCardPortal: typeof import('reka-ui')['HoverCardPortal']
    HoverCardRoot: typeof import('reka-ui')['HoverCardRoot']
    HoverCardTrigger: typeof import('reka-ui')['HoverCardTrigger']
    Label: typeof import('reka-ui')['Label']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScrollAreaRoot: typeof import('reka-ui')['ScrollAreaRoot']
    ScrollAreaScrollbar: typeof import('reka-ui')['ScrollAreaScrollbar']
    ScrollAreaThumb: typeof import('reka-ui')['ScrollAreaThumb']
    ScrollAreaViewport: typeof import('reka-ui')['ScrollAreaViewport']
    SwitchRoot: typeof import('reka-ui')['SwitchRoot']
    SwitchThumb: typeof import('reka-ui')['SwitchThumb']
    VisuallyHidden: typeof import('reka-ui')['VisuallyHidden']
  }
}
