/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AutocompleteAnchor: typeof import('reka-ui')['AutocompleteAnchor']
    AutocompleteContent: typeof import('reka-ui')['AutocompleteContent']
    AutocompleteEmpty: typeof import('reka-ui')['AutocompleteEmpty']
    AutocompleteGroup: typeof import('reka-ui')['AutocompleteGroup']
    AutocompleteInput: typeof import('reka-ui')['AutocompleteInput']
    AutocompleteItem: typeof import('reka-ui')['AutocompleteItem']
    AutocompleteLabel: typeof import('reka-ui')['AutocompleteLabel']
    AutocompleteRoot: typeof import('reka-ui')['AutocompleteRoot']
    AutocompleteSeparator: typeof import('reka-ui')['AutocompleteSeparator']
    AutocompleteTrigger: typeof import('reka-ui')['AutocompleteTrigger']
    AutocompleteViewport: typeof import('reka-ui')['AutocompleteViewport']
    NavigationMenuList: typeof import('reka-ui')['NavigationMenuList']
    NavigationMenuRoot: typeof import('reka-ui')['NavigationMenuRoot']
    ProgressIndicator: typeof import('reka-ui')['ProgressIndicator']
    ProgressRoot: typeof import('reka-ui')['ProgressRoot']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScrollAreaRoot: typeof import('reka-ui')['ScrollAreaRoot']
    ScrollAreaScrollbar: typeof import('reka-ui')['ScrollAreaScrollbar']
    ScrollAreaThumb: typeof import('reka-ui')['ScrollAreaThumb']
    ScrollAreaViewport: typeof import('reka-ui')['ScrollAreaViewport']
  }
}
