/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ComDialog: typeof import('./../components/comDialog.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScrollAreaRoot: typeof import('reka-ui')['ScrollAreaRoot']
    ScrollAreaScrollbar: typeof import('reka-ui')['ScrollAreaScrollbar']
    ScrollAreaThumb: typeof import('reka-ui')['ScrollAreaThumb']
    ScrollAreaViewport: typeof import('reka-ui')['ScrollAreaViewport']
  }
}
